import React from 'react';
import { UseFormRegister, FieldErrors } from 'react-hook-form';
import { Metadata } from '../types/metadata';

interface FinalDetailsFormProps {
  register: UseFormRegister<Metadata>;
  errors: FieldErrors<Metadata>;
}

const FinalDetailsForm: React.FC<FinalDetailsFormProps> = ({ register, errors }) => {
  return (
    <div className="final-details-form">
      <h2>Final Details</h2>
      <p className="step-description">
        <strong>Almost done!</strong> Now that your prompts are ready, complete these final fields with the information you'll receive from the portal after processing.
      </p>
      
      <div className="form-grid">
        <div className="form-group">
          <label htmlFor="uuid">UUID *</label>
          <input
            id="uuid"
            type="text"
            {...register('uuid')}
            placeholder="Enter UUID from portal (available after first prompt completion)"
          />
          {errors.uuid && <span className="error">{errors.uuid.message}</span>}
          <small className="field-help">
            This UUID is generated by the portal after the first prompt is completed.
          </small>
        </div>

        <div className="form-group">
          <label htmlFor="hfi_id">HFI ID *</label>
          <input
            id="hfi_id"
            type="text"
            {...register('hfi_id')}
            placeholder="Enter HFI ID from portal (available after first prompt completion)"
          />
          {errors.hfi_id && <span className="error">{errors.hfi_id.message}</span>}
          <small className="field-help">
            The Human-Feedback Interface ID is provided by the portal after the first prompt is processed.
          </small>
        </div>

        <div className="form-group">
          <label htmlFor="final_codebase_link">Final Codebase Link *</label>
          <input
            id="final_codebase_link"
            type="url"
            {...register('final_codebase_link')}
            placeholder="Enter final codebase URL (available after all prompts are completed)"
          />
          {errors.final_codebase_link && <span className="error">{errors.final_codebase_link.message}</span>}
          <small className="field-help">
            Link to the final codebase after all prompts have been processed and work is complete.
          </small>
        </div>
      </div>

      <div className="final-details-info">
        <div className="info-box">
          <h4>📋 When to fill these fields:</h4>
          <ul>
            <li><strong>UUID & HFI ID:</strong> Available after the first prompt is completed in the portal</li>
            <li><strong>Final Codebase Link:</strong> Available after all prompts are processed and final code is ready</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default FinalDetailsForm;
